name: Sigma Release Package

# Build Sigma and deploy to Github maven repository on each push to the
# master branch.

# Note that releases should only be created from the master repository
# It would be nice if we could enforce that.

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: lambda-repo # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: REPO_USERNAME # env variable for username in deploy
        server-password: REPO_TOKEN # env variable for token in deploy:  
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Publish to Github Maven repository
      run: mvn deploy
      env:
        REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        
        
